### ISSUE TITLE
Making this work on the Posts page

### ISSUE THREAD

**Issue by srikat** [studiopress/genesis-simple-sidebars#28]
Is there a way to make the user selected sidebar from the plugin's metabox on the Posts page (a static Page set at Settings > Reading) appear on the front end?

At the moment it does not work and widgets in the default Primary Sidebar continue to appear on the Posts page in spite of a different sidebar selected for the Primary Sidebar location in the back end.

This has also been asked in the wp.org forum 2 years ago here: https://wordpress.org/support/topic/custom-sidebar-for-posts-page-not-possible/

**Comment by GaryJones** [comment]
A quick glance suggests [this method](https://github.com/copyblogger/genesis-simple-sidebars/blob/87b2e738d4a44c74554930bdb29d4fe9436494d3/includes/class-genesis-simple-sidebars-core.php#L81-L109) doesn't cover all of the conditions - I can see `is_date()` (and variants) missing as well, for instance.
