### ISSUE TITLE
PODS Custom Taxonomies

### ISSUE THREAD

**Issue by mchildress** [studiopress/genesis-simple-sidebars#34]
When I use PODS to create a custom post type and three simple custom taxonomies, I am unable to assign a sidebar to those custom taxonomies similar to how I can with native post categories like the screen shot below with those sidebar settings appearing below the description.  Thanks for any input/fix you could provide.

![screen shot 2019-02-07 at 1 14 46 pm](https://user-images.githubusercontent.com/6842680/52443448-8be83980-2ada-11e9-8230-f1c5dcb25f6e.png)

**Comment by nickcernis** [comment]
It looks like Pods registers the taxonomies after Simple Sidebars checks for taxonomies to add the sidebar selector to:

<img width="1611" alt="screenshot 2019-02-07 at 23 26 45" src="https://user-images.githubusercontent.com/647669/52447105-1d35cb00-2b30-11e9-9a27-6e8e90a663d0.png">

@mchildress If you change this line in `wp-content/plugins/genesis-simple-sidebars/includes/class-genesis-simple-sidebars-term.php`:

`add_action( 'init', array( $this, 'add_term_fields' ) );`

To look like this:

`add_action( 'init', array( $this, 'add_term_fields' ), 12 );`

Does that solve the issue for you and make the sidebar selector appear in your taxonomy admin page?

Your taxonomy will still have to be 'public' in the Pods settings for this to work.

**Comment by mchildress** [comment]
Thanks so much Nick!  That works.  Any possibility of getting this into the latest plugin update?

**Comment by nickcernis** [comment]
@mchildress Thanks for confirming! I committed the code to fix this for the next release in https://github.com/studiopress/genesis-simple-sidebars/pull/35, although I don't have a timeline for the next update just yet.

**Comment by mchildress** [comment]
Great news.  Thanks again Nick.
